//! Integration tests for the activate module.

use envo::activate::snapshot::ShellType;
use envo::activate::Activator;
use envo::lockfile::{Lockfile, PackageResolution, ResolvedPackage, LOCKFILE_VERSION};
use envo::manifest::Manifest;
use envo::realize::ShimManifest;
use std::collections::HashMap;
use tempfile::tempdir;

fn setup() -> (tempfile::TempDir, Manifest, Lockfile, ShimManifest) {
    let tmp = tempdir().unwrap();
    std::fs::create_dir_all(tmp.path().join(".envo/bin")).unwrap();

    let manifest = Manifest::from_str(
        r#"
[project]
name = "integration-test"

[packages]
ripgrep = "*"
jq = "*"

[vars]
EDITOR = "vim"
DATABASE_URL = "postgres://localhost/test"
API_KEY = "secret-123"

[hook]
on-activate = '''
echo "Environment activated!"
'''
"#,
    )
    .unwrap();

    let mut systems = HashMap::new();
    systems.insert(
        "x86_64-linux".to_string(),
        PackageResolution {
            store_path: "/nix/store/abc-ripgrep".to_string(),
            resolved_attr: "ripgrep".to_string(),
        },
    );
    let mut packages = HashMap::new();
    packages.insert("ripgrep".to_string(), ResolvedPackage { systems });

    let lockfile = Lockfile {
        version: LOCKFILE_VERSION,
        nixpkgs_revision: "test-rev".to_string(),
        manifest_hash: "test-hash-123".to_string(),
        packages,
    };

    let shim_manifest = ShimManifest::new();

    (tmp, manifest, lockfile, shim_manifest)
}

#[test]
fn test_full_activation_cycle_posix() {
    let (tmp, manifest, lockfile, shim_manifest) = setup();
    let activator = Activator::new(tmp.path());

    // Generate
    let snapshot = activator
        .generate_snapshot(&manifest, &lockfile, &shim_manifest, ShellType::Bash)
        .unwrap();

    // Verify all expected content
    assert!(snapshot.contains("export PATH="));
    assert!(snapshot.contains(".envo/bin:$PATH"));
    assert!(snapshot.contains("export ENVO_ENV=\"integration-test\""));
    assert!(snapshot.contains("export EDITOR=\"vim\""));
    assert!(snapshot.contains("export DATABASE_URL=\"postgres://localhost/test\""));
    assert!(snapshot.contains("export API_KEY=\"secret-123\""));
    assert!(snapshot.contains("echo \"Environment activated!\""));
    assert!(snapshot.contains("# lockfile_hash: test-hash-123"));

    // Deactivate
    let deact = activator
        .generate_deactivation(&manifest, ShellType::Bash)
        .unwrap();

    assert!(deact.contains("unset ENVO_ENV"));
    assert!(deact.contains("unset EDITOR"));
    assert!(deact.contains("unset DATABASE_URL"));
    assert!(deact.contains("unset API_KEY"));
}

#[test]
fn test_full_activation_cycle_fish() {
    let (tmp, manifest, lockfile, shim_manifest) = setup();
    let activator = Activator::new(tmp.path());

    let snapshot = activator
        .generate_snapshot(&manifest, &lockfile, &shim_manifest, ShellType::Fish)
        .unwrap();

    assert!(snapshot.contains("set -gx PATH"));
    assert!(snapshot.contains("set -gx ENVO_ENV integration-test"));
    assert!(snapshot.contains("set -gx EDITOR \"vim\""));
    assert!(!snapshot.contains("export "));
}

#[test]
fn test_env_vars_for_programmatic_access() {
    let (tmp, manifest, lockfile, shim_manifest) = setup();
    let activator = Activator::new(tmp.path());

    let env = activator
        .env_vars(&manifest, &lockfile, &shim_manifest)
        .unwrap();

    assert_eq!(env["ENVO_ENV"], "integration-test");
    assert_eq!(env["EDITOR"], "vim");
    assert_eq!(env["DATABASE_URL"], "postgres://localhost/test");
    assert_eq!(env["API_KEY"], "secret-123");
    assert!(env["ENVO_BIN_DIR"].contains(".envo/bin"));
}

#[test]
fn test_save_and_read_snapshot() {
    let (tmp, manifest, lockfile, shim_manifest) = setup();
    let activator = Activator::new(tmp.path());

    let path = activator
        .save_snapshot(&manifest, &lockfile, &shim_manifest, ShellType::Bash)
        .unwrap();

    assert!(path.exists());
    let content = std::fs::read_to_string(&path).unwrap();
    assert!(content.contains("export ENVO_ENV"));
    assert!(content.starts_with("# Generated by envo"));
}

#[test]
fn test_snapshot_no_subshell_anywhere() {
    let (tmp, manifest, lockfile, shim_manifest) = setup();
    let activator = Activator::new(tmp.path());

    for shell in [ShellType::Bash, ShellType::Zsh, ShellType::Fish] {
        let snapshot = activator
            .generate_snapshot(&manifest, &lockfile, &shim_manifest, shell)
            .unwrap();

        assert!(!snapshot.contains("exec bash"), "snapshot must not exec bash");
        assert!(!snapshot.contains("exec zsh"), "snapshot must not exec zsh");
        assert!(!snapshot.contains("bash -c"), "snapshot must not use bash -c");
    }
}
