#!/usr/bin/env bash
# Integration test: activation snapshot generation and sourcing
# Tests the end-to-end activation flow without requiring Nix
# Usage: bash tests/integration/test_activate.sh

set -euo pipefail

PASS=0
FAIL=0

pass() { echo "  ✓ $1"; PASS=$((PASS + 1)); }
fail() { echo "  ✗ $1"; FAIL=$((FAIL + 1)); }

echo "=== Integration Test: Activation Snapshot ==="
echo ""

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

PROJECT="$TMPDIR/my-project"
mkdir -p "$PROJECT/.envo/bin"

# ── Setup: Create a fake snapshot (simulating what the Rust code generates) ──

echo "Test 1: Source a POSIX activation snapshot"

BIN_DIR="$PROJECT/.envo/bin"

# Create a fake shim so we can verify PATH works
cat > "$BIN_DIR/my-tool" << 'EOF'
#!/usr/bin/env bash
echo "my-tool v1.0"
EOF
chmod +x "$BIN_DIR/my-tool"

# Generate a snapshot manually (simulating Activator output)
cat > "$PROJECT/.envo/env-snapshot.sh" << SNAPSHOT
# Generated by envo — do not edit
# lockfile_hash: test-hash-abc

export PATH="$BIN_DIR:\$PATH"
export ENVO_ENV="my-project"
export ENVO_DIR="$PROJECT"

export API_KEY="secret-123"
export EDITOR="vim"
export MY_VAR="hello world"

# On-activate hook (runs once per activation)
if [ -z "\$ENVO_HOOK_DONE" ]; then
    export ENVO_HOOK_DONE=1
    echo "Hook executed!"
fi
SNAPSHOT

# Source the snapshot in a subshell to test without polluting this shell
ACTIVATE_OUTPUT=$(bash -c "
    source '$PROJECT/.envo/env-snapshot.sh'
    echo \"PATH_CHECK=\$(echo \$PATH | grep -c '.envo/bin')\"
    echo \"ENVO_ENV=\$ENVO_ENV\"
    echo \"ENVO_DIR=\$ENVO_DIR\"
    echo \"EDITOR=\$EDITOR\"
    echo \"MY_VAR=\$MY_VAR\"
    echo \"API_KEY=\$API_KEY\"
    echo \"HOOK_DONE=\$ENVO_HOOK_DONE\"
    my-tool
" 2>&1)

if echo "$ACTIVATE_OUTPUT" | grep -q "PATH_CHECK=1"; then
    pass "PATH contains .envo/bin"
else
    fail "PATH does not contain .envo/bin"
fi

if echo "$ACTIVATE_OUTPUT" | grep -q "ENVO_ENV=my-project"; then
    pass "ENVO_ENV is set"
else
    fail "ENVO_ENV not set: $ACTIVATE_OUTPUT"
fi

if echo "$ACTIVATE_OUTPUT" | grep -q "EDITOR=vim"; then
    pass "EDITOR var is set"
else
    fail "EDITOR not set"
fi

if echo "$ACTIVATE_OUTPUT" | grep -q "MY_VAR=hello world"; then
    pass "MY_VAR is set"
else
    fail "MY_VAR not set"
fi

if echo "$ACTIVATE_OUTPUT" | grep -q "API_KEY=secret-123"; then
    pass "API_KEY is set"
else
    fail "API_KEY not set"
fi

if echo "$ACTIVATE_OUTPUT" | grep -q "Hook executed!"; then
    pass "on-activate hook ran"
else
    fail "hook did not run"
fi

if echo "$ACTIVATE_OUTPUT" | grep -q "HOOK_DONE=1"; then
    pass "ENVO_HOOK_DONE is set"
else
    fail "ENVO_HOOK_DONE not set"
fi

if echo "$ACTIVATE_OUTPUT" | grep -q "my-tool v1.0"; then
    pass "shim is executable via PATH"
else
    fail "shim not found via PATH"
fi

# ── Test 2: Hook doesn't re-run on nested activation ──────────────

echo ""
echo "Test 2: Hook guard prevents re-execution"

NESTED_OUTPUT=$(bash -c "
    source '$PROJECT/.envo/env-snapshot.sh' 2>&1
    source '$PROJECT/.envo/env-snapshot.sh' 2>&1
" 2>&1)

HOOK_COUNT=$(echo "$NESTED_OUTPUT" | grep -c "Hook executed!" || true)
if [ "$HOOK_COUNT" -eq 1 ]; then
    pass "hook ran exactly once on nested activation"
else
    fail "hook ran $HOOK_COUNT times (expected 1)"
fi

# ── Test 3: Deactivation ──────────────────────────────────────────

echo ""
echo "Test 3: Deactivation unsets variables"

cat > "$PROJECT/.envo/deactivate.sh" << DEACT
# Generated by envo — deactivation

export PATH=\$(echo "\$PATH" | sed "s|$BIN_DIR:||g; s|:$BIN_DIR||g; s|$BIN_DIR||g")
unset ENVO_ENV
unset ENVO_DIR
unset ENVO_HOOK_DONE
unset EDITOR
unset MY_VAR
unset API_KEY
DEACT

DEACT_OUTPUT=$(bash -c "
    source '$PROJECT/.envo/env-snapshot.sh' 2>/dev/null
    source '$PROJECT/.envo/deactivate.sh' 2>/dev/null
    echo \"ENVO_ENV=\${ENVO_ENV:-UNSET}\"
    echo \"EDITOR=\${EDITOR:-UNSET}\"
    echo \"PATH_CHECK=\$(echo \$PATH | grep -c '.envo/bin')\"
" 2>&1)

if echo "$DEACT_OUTPUT" | grep -q "ENVO_ENV=UNSET"; then
    pass "ENVO_ENV unset after deactivation"
else
    fail "ENVO_ENV still set after deactivation"
fi

if echo "$DEACT_OUTPUT" | grep -q "EDITOR=UNSET"; then
    pass "EDITOR unset after deactivation"
else
    fail "EDITOR still set after deactivation"
fi

if echo "$DEACT_OUTPUT" | grep -q "PATH_CHECK=0"; then
    pass "PATH cleaned after deactivation"
else
    fail "PATH still contains .envo/bin after deactivation"
fi

# ── Test 4: Activation speed ──────────────────────────────────────

echo ""
echo "Test 4: Activation speed"

# Time sourcing the snapshot 100 times
START_NS=$(date +%s%N 2>/dev/null || echo "0")
for i in $(seq 1 100); do
    bash -c "source '$PROJECT/.envo/env-snapshot.sh'" 2>/dev/null
done
END_NS=$(date +%s%N 2>/dev/null || echo "0")

if [ "$START_NS" != "0" ] && [ "$END_NS" != "0" ]; then
    ELAPSED_MS=$(( (END_NS - START_NS) / 1000000 ))
    PER_ACTIVATION_MS=$(( ELAPSED_MS / 100 ))
    echo "  ℹ 100 activations in ${ELAPSED_MS}ms (${PER_ACTIVATION_MS}ms each)"

    if [ "$PER_ACTIVATION_MS" -lt 10 ]; then
        pass "activation is under 10ms per invocation"
    elif [ "$PER_ACTIVATION_MS" -lt 100 ]; then
        pass "activation is under 100ms (${PER_ACTIVATION_MS}ms) — acceptable"
    else
        fail "activation is ${PER_ACTIVATION_MS}ms — too slow"
    fi
else
    pass "timing not available (date +%s%N unsupported), covered by unit tests"
fi

# ── Results ────────────────────────────────────────────────────────

echo ""
echo "=== Results ==="
echo "  Passed: $PASS"
echo "  Failed: $FAIL"
echo ""

if [ "$FAIL" -gt 0 ]; then
    echo "SOME TESTS FAILED"
    exit 1
else
    echo "ALL TESTS PASSED"
    exit 0
fi
