//! Shell-specific snapshot rendering.
//!
//! Generates sourceable shell scripts that activate an envo environment
//! by setting PATH, environment variables, and running hooks. Supports
//! bash/zsh (same syntax) and fish (different syntax).

use std::collections::HashMap;

/// Supported shell types for snapshot generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellType {
    /// Bash and Zsh share POSIX-compatible export syntax.
    Bash,
    Zsh,
    /// Fish uses `set -gx` instead of `export`.
    Fish,
}

impl ShellType {
    /// Parse a shell type from a string (e.g., from $SHELL or --shell flag).
    pub fn from_str(s: &str) -> Option<Self> {
        let basename = s.rsplit('/').next().unwrap_or(s);
        match basename {
            "bash" => Some(Self::Bash),
            "zsh" => Some(Self::Zsh),
            "fish" => Some(Self::Fish),
            _ => None,
        }
    }

    /// Detect the current shell from the $SHELL environment variable.
    pub fn detect() -> Self {
        std::env::var("SHELL")
            .ok()
            .and_then(|s| Self::from_str(&s))
            .unwrap_or(Self::Bash)
    }

    /// Whether this shell uses POSIX export syntax.
    pub fn is_posix(&self) -> bool {
        matches!(self, Self::Bash | Self::Zsh)
    }

    /// The file extension for snapshot files of this shell type.
    pub fn snapshot_extension(&self) -> &'static str {
        match self {
            Self::Bash | Self::Zsh => "sh",
            Self::Fish => "fish",
        }
    }
}

/// Render an activation snapshot for bash/zsh.
pub fn render_posix_snapshot(
    bin_dir: &str,
    project_name: &str,
    project_dir: &str,
    vars: &HashMap<String, String>,
    lockfile_hash: &str,
    hook_script: Option<&str>,
    python_paths: &[String],
) -> String {
    let mut out = String::with_capacity(1024);

    out.push_str(&format!(
        "# Generated by envo — do not edit\n# lockfile_hash: {lockfile_hash}\n\n"
    ));

    out.push_str(&format!("export PATH=\"{bin_dir}:$PATH\"\n"));
    out.push_str(&format!("export ENVO_ENV=\"{project_name}\"\n"));
    out.push_str(&format!("export ENVO_DIR=\"{project_dir}\"\n"));

    if !python_paths.is_empty() {
        let joined = python_paths.join(":");
        out.push_str(&format!(
            "export PYTHONPATH=\"{joined}${{PYTHONPATH:+:$PYTHONPATH}}\"\n"
        ));
    }

    if !vars.is_empty() {
        out.push('\n');
        let mut sorted_vars: Vec<_> = vars.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());
        for (key, value) in sorted_vars {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!("export {key}=\"{escaped}\"\n"));
        }
    }

    if let Some(hook) = hook_script {
        let trimmed = hook.trim();
        if !trimmed.is_empty() {
            out.push_str("\n# On-activate hook (runs once per activation)\n");
            out.push_str("if [ -z \"$ENVO_HOOK_DONE\" ]; then\n");
            out.push_str("    export ENVO_HOOK_DONE=1\n");
            for line in trimmed.lines() {
                out.push_str(&format!("    {line}\n"));
            }
            out.push_str("fi\n");
        }
    }

    out
}

/// Render an activation snapshot for fish shell.
pub fn render_fish_snapshot(
    bin_dir: &str,
    project_name: &str,
    project_dir: &str,
    vars: &HashMap<String, String>,
    lockfile_hash: &str,
    python_paths: &[String],
) -> String {
    let mut out = String::with_capacity(1024);

    out.push_str(&format!(
        "# Generated by envo — do not edit\n# lockfile_hash: {lockfile_hash}\n\n"
    ));

    out.push_str(&format!("set -gx PATH {bin_dir} $PATH\n"));
    out.push_str(&format!("set -gx ENVO_ENV {project_name}\n"));
    out.push_str(&format!("set -gx ENVO_DIR {project_dir}\n"));

    if !python_paths.is_empty() {
        // Fish prepends to PYTHONPATH using its list syntax
        for path in python_paths.iter().rev() {
            out.push_str(&format!("set -gx PYTHONPATH {path} $PYTHONPATH\n"));
        }
    }

    if !vars.is_empty() {
        out.push('\n');
        let mut sorted_vars: Vec<_> = vars.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());
        for (key, value) in sorted_vars {
            out.push_str(&format!("set -gx {key} \"{value}\"\n"));
        }
    }

    out
}

/// Render a deactivation script for bash/zsh.
pub fn render_posix_deactivation(
    bin_dir: &str,
    var_keys: &[&str],
    had_python_paths: bool,
) -> String {
    let mut out = String::new();

    out.push_str("# Generated by envo — deactivation\n\n");
    out.push_str(&format!(
        "export PATH=$(echo \"$PATH\" | sed 's|{bin_dir}:||g; s|:{bin_dir}||g; s|{bin_dir}||g')\n"
    ));
    out.push_str("unset ENVO_ENV\n");
    out.push_str("unset ENVO_DIR\n");
    out.push_str("unset ENVO_HOOK_DONE\n");

    if had_python_paths {
        out.push_str("unset PYTHONPATH\n");
    }

    for key in var_keys {
        out.push_str(&format!("unset {key}\n"));
    }

    out
}

/// Render a deactivation script for fish.
pub fn render_fish_deactivation(
    bin_dir: &str,
    var_keys: &[&str],
    had_python_paths: bool,
) -> String {
    let mut out = String::new();

    out.push_str("# Generated by envo — deactivation\n\n");
    out.push_str(&format!(
        "set -l idx (contains -i {bin_dir} $PATH); and set -e PATH[$idx]\n"
    ));
    out.push_str("set -e ENVO_ENV\n");
    out.push_str("set -e ENVO_DIR\n");
    out.push_str("set -e ENVO_HOOK_DONE\n");

    if had_python_paths {
        out.push_str("set -e PYTHONPATH\n");
    }

    for key in var_keys {
        out.push_str(&format!("set -e {key}\n"));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_vars() -> HashMap<String, String> {
        let mut vars = HashMap::new();
        vars.insert("EDITOR".to_string(), "vim".to_string());
        vars.insert("DATABASE_URL".to_string(), "postgres://localhost/dev".to_string());
        vars.insert("RUST_LOG".to_string(), "debug".to_string());
        vars
    }

    #[test]
    fn test_posix_snapshot_basic() {
        let snapshot = render_posix_snapshot(
            "/home/user/project/.envo/bin",
            "my-app",
            "/home/user/project",
            &HashMap::new(),
            "abc123",
            None,
            &[],
        );

        assert!(snapshot.contains("# Generated by envo"));
        assert!(snapshot.contains("# lockfile_hash: abc123"));
        assert!(snapshot.contains("export PATH=\"/home/user/project/.envo/bin:$PATH\""));
        assert!(snapshot.contains("export ENVO_ENV=\"my-app\""));
        assert!(snapshot.contains("export ENVO_DIR=\"/home/user/project\""));
        assert!(!snapshot.contains("PYTHONPATH"));
    }

    #[test]
    fn test_posix_snapshot_with_python_paths() {
        let paths = vec![
            "/nix/store/abc-python3.12-torch-2.11.0/lib/python3.12/site-packages".to_string(),
            "/nix/store/def-python3.12-torchvision-0.26.0/lib/python3.12/site-packages".to_string(),
        ];
        let snapshot = render_posix_snapshot(
            "/p/.envo/bin", "ml", "/p", &HashMap::new(), "hash", None, &paths,
        );

        assert!(snapshot.contains("export PYTHONPATH="));
        assert!(snapshot.contains("python3.12-torch"));
        assert!(snapshot.contains("python3.12-torchvision"));
        assert!(snapshot.contains("${PYTHONPATH:+:$PYTHONPATH}"));
    }

    #[test]
    fn test_posix_snapshot_with_vars() {
        let vars = sample_vars();
        let snapshot = render_posix_snapshot(
            "/p/.envo/bin", "test", "/p", &vars, "hash", None, &[],
        );

        assert!(snapshot.contains("export DATABASE_URL=\"postgres://localhost/dev\""));
        assert!(snapshot.contains("export EDITOR=\"vim\""));
        assert!(snapshot.contains("export RUST_LOG=\"debug\""));
    }

    #[test]
    fn test_posix_snapshot_vars_are_sorted() {
        let vars = sample_vars();
        let snapshot = render_posix_snapshot(
            "/p/.envo/bin", "test", "/p", &vars, "hash", None, &[],
        );

        let db_pos = snapshot.find("DATABASE_URL").unwrap();
        let editor_pos = snapshot.find("EDITOR").unwrap();
        let rust_pos = snapshot.find("RUST_LOG").unwrap();

        assert!(db_pos < editor_pos);
        assert!(editor_pos < rust_pos);
    }

    #[test]
    fn test_posix_snapshot_with_hook() {
        let snapshot = render_posix_snapshot(
            "/p/.envo/bin", "test", "/p", &HashMap::new(), "hash",
            Some("echo \"Hello!\"\nexport FOO=bar"),
            &[],
        );

        assert!(snapshot.contains("if [ -z \"$ENVO_HOOK_DONE\" ]"));
        assert!(snapshot.contains("export ENVO_HOOK_DONE=1"));
        assert!(snapshot.contains("echo \"Hello!\""));
        assert!(snapshot.contains("export FOO=bar"));
        assert!(snapshot.contains("fi"));
    }

    #[test]
    fn test_posix_snapshot_no_subshell() {
        let snapshot = render_posix_snapshot(
            "/p/.envo/bin", "test", "/p", &sample_vars(), "hash",
            Some("echo hello"),
            &[],
        );

        assert!(!snapshot.contains("bash -c"));
        assert!(!snapshot.contains("$SHELL"));
        assert!(!snapshot.contains("exec bash"));
        assert!(!snapshot.contains("exec zsh"));
    }

    #[test]
    fn test_posix_snapshot_escapes_quotes() {
        let mut vars = HashMap::new();
        vars.insert("MSG".to_string(), "say \"hello\"".to_string());
        let snapshot = render_posix_snapshot(
            "/p/.envo/bin", "test", "/p", &vars, "hash", None, &[],
        );

        assert!(snapshot.contains(r#"export MSG="say \"hello\"""#));
    }

    #[test]
    fn test_fish_snapshot_basic() {
        let snapshot = render_fish_snapshot(
            "/p/.envo/bin", "my-app", "/p", &HashMap::new(), "abc123", &[],
        );

        assert!(snapshot.contains("# Generated by envo"));
        assert!(snapshot.contains("set -gx PATH /p/.envo/bin $PATH"));
        assert!(snapshot.contains("set -gx ENVO_ENV my-app"));
        assert!(!snapshot.contains("export "));
        assert!(!snapshot.contains("PYTHONPATH"));
    }

    #[test]
    fn test_fish_snapshot_with_python_paths() {
        let paths = vec![
            "/nix/store/abc-python3.12-torch-2.11.0/lib/python3.12/site-packages".to_string(),
        ];
        let snapshot = render_fish_snapshot(
            "/p/.envo/bin", "ml", "/p", &HashMap::new(), "hash", &paths,
        );

        assert!(snapshot.contains("set -gx PYTHONPATH"));
        assert!(snapshot.contains("python3.12-torch"));
    }

    #[test]
    fn test_fish_snapshot_with_vars() {
        let vars = sample_vars();
        let snapshot = render_fish_snapshot(
            "/p/.envo/bin", "test", "/p", &vars, "hash", &[],
        );

        assert!(snapshot.contains("set -gx EDITOR \"vim\""));
        assert!(snapshot.contains("set -gx RUST_LOG \"debug\""));
    }

    #[test]
    fn test_posix_deactivation_without_python() {
        let deact = render_posix_deactivation(
            "/p/.envo/bin",
            &["EDITOR", "DATABASE_URL"],
            false,
        );

        assert!(deact.contains("unset ENVO_ENV"));
        assert!(deact.contains("unset ENVO_DIR"));
        assert!(deact.contains("unset ENVO_HOOK_DONE"));
        assert!(deact.contains("unset EDITOR"));
        assert!(deact.contains("unset DATABASE_URL"));
        assert!(!deact.contains("PYTHONPATH"));
    }

    #[test]
    fn test_posix_deactivation_with_python() {
        let deact = render_posix_deactivation("/p/.envo/bin", &[], true);

        assert!(deact.contains("unset PYTHONPATH"));
    }

    #[test]
    fn test_fish_deactivation() {
        let deact = render_fish_deactivation("/p/.envo/bin", &["EDITOR"], false);

        assert!(deact.contains("set -e ENVO_ENV"));
        assert!(deact.contains("set -e EDITOR"));
        assert!(deact.contains("contains -i"));
        assert!(!deact.contains("PYTHONPATH"));
    }

    #[test]
    fn test_fish_deactivation_with_python() {
        let deact = render_fish_deactivation("/p/.envo/bin", &[], true);

        assert!(deact.contains("set -e PYTHONPATH"));
    }

    #[test]
    fn test_shell_type_detection() {
        assert_eq!(ShellType::from_str("/bin/bash"), Some(ShellType::Bash));
        assert_eq!(ShellType::from_str("/usr/bin/zsh"), Some(ShellType::Zsh));
        assert_eq!(ShellType::from_str("/usr/local/bin/fish"), Some(ShellType::Fish));
        assert_eq!(ShellType::from_str("bash"), Some(ShellType::Bash));
        assert_eq!(ShellType::from_str("/bin/sh"), None);
    }

    #[test]
    fn test_shell_type_is_posix() {
        assert!(ShellType::Bash.is_posix());
        assert!(ShellType::Zsh.is_posix());
        assert!(!ShellType::Fish.is_posix());
    }

    #[test]
    fn test_empty_hook_not_rendered() {
        let snapshot = render_posix_snapshot(
            "/p/.envo/bin", "test", "/p", &HashMap::new(), "hash",
            Some("  \n  \n  "),
            &[],
        );

        assert!(!snapshot.contains("ENVO_HOOK_DONE"));
    }
}